name: .NET Framework 4.6.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Build
      run: msbuild  framework/ScepClientConsole.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: scepclient-win-x64
        path: |
          framework/bin/Release/ScepClientConsole.exe
          framework/bin/Release/ScepClientConsole.exe.config
          framework/bin/Release/*.dll