name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore -r win-x64
    - name: Build
      run: dotnet build --configuration Release --no-restore -r win-x64
    - name: Publish
      run: dotnet publish --configuration Release --no-restore -r win-x64 -p:PublishSingleFile=true
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: scepclient-win-x64
        path: /bin/Release/netcoreapp3.1/win-x64/publish/*